services:
  sumary-and-text-to-speech:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
     GROQ_API_KEY: ${GROQ_API_KEY:-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}


